### PR TITLE
feat: Shadow DOM

### LINKED ISSUE #7: Web Components support?
Are there any plans to make it possible to just apply this to a single web component without changing any global state? For example with https://lit.dev/ ?

### PR DESCRIPTION
**Pull request by Marshal27**
This PR closes #7 

I am still running it through its paces on my project, but, wanted to get a PR up so the team can get eyes on the impl/present thoughts or feedback.

### CODE REVIEW

**Comment by Marshal27** [comment]
sorry for the churn, believe this is ready for review/feedback.

**Comment by Marshal27** [comment]
Not sure that I am happy with the refactor to support `:host` selectors... it works, somewhat, however, `:host([attribute])` will not because the `container-type` is not being applied to the `computedStyles` for the host in firefox for this selector combination. 

Overall this enhancement works except for this fringe case.

**Comment by Marshal27** [comment]
rebased commits

**Comment by jared-christensen** [comment]
Is this ready?

**Comment by Marshal27** [comment]
> Is this ready? I'm ready to start using it :)

it is on my end, just need final review/approval from a project maintainer.

**Comment by devknoll** [comment]
Thanks for putting this together -- it's a great start!

Thoughts on constructible stylesheets:
* I think we need to monkeypatch `CSSStyleSheet.replace` and `CSSStyleSheet.replaceSync` so we can run the main transform function on them, since invalid rules (e.g. `@container` on older browsers) won't appear in the CSSOM. 
* `CSSStyleSheet.replaceSync` isn't available on all supported browsers, so we'll need to be careful when we call it.
* Rather than associating transformed styles with a DOM node, it seems like we should just associate them with the `CSSStyleSheet`. We likely want to continue to use the DOM to transform `<style>` and `<link>`, but associate the container descriptors with the `CSSStyleSheet` for that node.
* It might be easiest to break constructible stylesheets/`adoptedStyleSheets` into a separate PR.

General thoughts:
* We need to be careful about which container descriptors (and other state, e.g. container conditions) nodes see. By default, nodes in a Shadow DOM shouldn't be able to query containers outside of it.
  * The easiest thing to do here would be to pass the set of query descriptors as part of the state/context. Note that I've got a PR in progress (#53) that makes this change.
  * Then when we create the controllers for the `DocumentElement` and any `ShadowRoot`s, we can source the appropriate descriptors, and pass them down the subtree via state.
* We need to handle `::slotted()` in addition to `:host`. Right now, we pass the selectors to `Element.matches()` to see if we need to apply container classes to a particular element. This won't work for the Shadow DOM, since they'll never pass. Instead, we'll likely want to take an approach similar to other pseudo elements, and apply a unique custom attribute to the host and any slotted elements.
  * As mentioned above, by default any selectors used in a Shadow DOM stylesheet should only apply to containers defined inside the Shadow DOM.
* Similarly, we also need to handle `::part()`, likely by applying a unique custom attribute to the parts inside the Shadow DOM.

**Comment by Marshal27** [comment]
@devknoll thank you for this feedback, it is very helpful!

Do you want me to continue working in this PR/branch? Or would you prefer that I start a new feature based on the [ Improve updating performance #53 ](https://github.com/GoogleChromeLabs/container-query-polyfill/pull/53/files#) branch and incorporate the ideas/concepts from this PR on top of those new impls/patterns?

**Comment by Marshal27** [comment]
closing this PR in favor of #57

**Pull request closed without merging**
