### PR TITLE
Fix any assertion in enum field

### PR DESCRIPTION
**Pull request by erdalcay**
Fixes `FIXME: lol` :)

### CODE REVIEW

**Comment by erdalcay** [comment]
Oh wow, I didn't know what a CLA was. @surma Can you do a 'rescan' if this PR is useful at all?

**Review by surma — APPROVED** [review]

**Comment by surma** [comment]
Oh, the CLA is the Contributor License Agreement. There should be a bot leaving a comment if you haven’t signed it before, but I guess the bot isn’t working.

Please go [here](https://cla.developers.google.com/clas) and sign the CLA, otherwise I am not allowed by Google to merge your code.

**Comment by erdalcay** [comment]
I actually did that and signed the CLA. 

By 'rescan' I was referring the detail of the [failed check](https://github.com/GoogleChromeLabs/container-query-polyfill/pull/4/checks?check_run_id=4328440641):

> 📝 If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. Once you've signed (or fixed any issues), please request a rescan from a repository manager.
>
> 🔁 Repository managers: You can rescan this PR by pressing the "Re-run" button to the left of this description.

So I assumed you could re-run the check.

**Comment by erdalcay** [comment]
I think we are good to go now.

Sorry for the headache.

**Comment by surma** [comment]
Cheers!

**Pull request merged**
